### ISSUE TITLE
If a TTL isn't specified on an event before it is processed by rate it will never expire

### ISSUE THREAD

**Issue by eric** [riemann/riemann#390]
I've run into a case where riemann is working as written but not as expected.

I had created the index like this to ensure all metrics have a TTL (which I believe I had picked up from the documentation somewhere):

``` clojure
(let [index (default :ttl 300
              (index))]
```

Later on I had the following, but found out that some of my rates had not ever expired even though I had not sent anything for that service for a very long time:

``` clojure
          (by [:host :service]
            (rate 5 index))
```

I was able to track down the problem to the fact that at some point I had sent events with no TTL set, and because my `default` logic happens right before the events are inserted into the `index`, the TTL is not set when `rate` is called.

This issue should impact `streams/top` as well (which may be what #389 is referring to).

The solution for this is to put the `default` logic at the start of the stream:

``` clojure
  (streams
    ; Make sure everything has some sort of TTL
    (default :ttl 300
```

**Comment by wickedshimmy** [comment]
Is there currently any way to express an infinite TTL?

Count this as my vote for that as a default if you'd like (mainly because the other behaviors are easy to obtain), but I have a number of events now where I just set some absurdly long timeframe (expiry isn't a concern, but I'd like to see the most recent value until it's updated, which happens inconsistently) in lieu of being able to do that.

**Comment by faxm0dem** [comment]
:+1: to infinity (and beyond)

**Comment by pyr** [comment]
@wickedshimmy yes, setting ttl to nil.

I think most are in favor of nil ttls meaning no expiry. This will have to be made more explicit in docs, a warn log when rate/top encounter nil ttl metrics might also be an option.
