### ISSUE TITLE
fixed-time-window doesn't seem to fire the vector of events by itself

### ISSUE THREAD

**Issue by joelapatatechaude** [riemann/riemann#563]
Maybe that something expected, but here is the thing:

```clojure
(where (service "HAHA")
prn
(fixed-time-window 2 prn))
```

Let's say I send an event with service "HAHA", and I wait 2 secs. I would expect the vector of (1 event) being fired automatically after 2 secs. It is not the case. It is only when fixed-time-window receives an event after the 2 sec delay that if fires the vector(s) of events.

Is that expected or is it a bug?

Is there a way to get a fixed-time-window that fires vectors by itself naturally?

**Comment by aphyr** [comment]
Yeah, we should port fixed-time-window to use part-time-simple.
On Jun 14, 2015 8:55 PM, Christophe Schmitz <notifications@github.com> wrote:Maybe that something expected, but here is the thing:

(where (service "HAHA")
prn
(fixed-time-window 2 prn))

Let's say I send an event with service "HAHA", and I wait 2 secs. I would expect the vector of (1 event) being fired automatically after 2 secs. It is not the case. It is only when fixed-time-window receives an event after the 2 sec delay that if fires the vector(s) of events.

Is that expected or is it a bug?

Is there a way to get a fixed-time-window that fires vectors by itself naturally?

**Comment by juise** [comment]
+1 for part-time-simple.

Right now I have to use fill-in-last with some tricky clojure code for push on vector from fixed-time-window/fixed-offset-time-window

**Comment by juiceblender** [comment]
With regards to this, does anyone know what would happen if, hypothetically, suppose the fixed time window is for 20 seconds and the host that's responsible for sending the event with service "HAHA" was deleted after having sent the event for 10 seconds and thus this event will never ever be sent again. Since nothing else will 'trigger' fixed-time-window to fire the vector, does what it already has just sit there indefinitely and consume memory?

**Comment by juise** [comment]
Seems to vector will sit there! I have fixed this problem with the follow block of code, it's a little bit ugly but works!


(defn rammer [e & children]
  "Pushes the accumulated metrics"
  (fn stream [events]
    (let [events     (group-by #(if (not= (:metric %) nil) :ok :nil) events)
          ok-events  (:ok events)
          nil-events (:nil events)]
      (cond
        ok-events  (call-rescue ok-events children)
        nil-events (let [event (first nil-events)
                         event (if (not= (:metric @e) nil) event (assoc event :state "expired"))]
                     (reinject event))))))

(defn sum [interval & children]
  "Calculate sum of event stream in time every interval seconds"
  (let [e (atom nil)]
    (by :service
      (fill-in-last 1 {:metric nil}
        (sdo
          (register e)
            (fixed-time-window interval
              (rammer e
                (apply smap folds/sum children))))))))

**Comment by juiceblender** [comment]
That's pretty neat, so it looks like (I'm not very good at Clojure) you reinject events every now and then to nudge fixed-time-window? Then you could try using batch instead? For me I've tried to move towards using percentiles since it doesn't suffer from this problem, and recently have been experimenting with part-time-fast.

**Comment by juise** [comment]
@pyr could you please point to commit where it has been fixed?

**Comment by pyr** [comment]
@juise we're not in the the part-time-simple situation yet, but this issue documents a workaround, next step is to have a PR which modifies the behavior of fixed-time-window.

**Comment by faxm0dem** [comment]
I'm currently testing @juise's workaround
