### ISSUE TITLE
Nanoseconds precision for timestamps

### ISSUE THREAD

**Issue by artditel** [riemann/riemann#590]
Do you have plans for this feature?
And if you don't, maybe we can discuss riemann interface.
For example it can be:
* a separate `nanoseconds` field for a fractional part
* a `precision` field like in influxdb with values `s`/`n`/`u` etc
* an optional decimal part for a timestamp, `12334524.123555` for example

**Comment by aphyr** [comment]
Since nobody actually has nanosecond resolution, I'm thinking the best option may be to rebase Riemann's timescale to long microseconds since epoch, which should cover a reasonable time range at reasonable resolution. That'll require a ground-up rewrite of all of riemann.streams and riemann.time, plus a thorough documentation effort, though.

**Comment by Kenuat** [comment]
for example Zabbix uses milliseconds only to distinguish several values which came during single second

**Comment by pyr** [comment]
hi, there are no immediate plans for subsecond resolutions, closing this until they are reconsidered
