### ISSUE TITLE
Undefined behavior in index expire

### ISSUE THREAD

**Issue by CAFxX** [riemann/riemann#616]
https://github.com/aphyr/riemann/blob/master/src/riemann/index.clj#L76

It is most likely [undefined behavior](http://docs.oracle.com/javase/7/docs/api/java/util/Map.html#values()) to modify a Map while iterating like this - except by using Iterator.remove() (that, by the way, should be way faster).

**Comment by AeroNotix** [comment]
java.util.Map is not the map representation being used here.

**Comment by CAFxX** [comment]
@AeroNotix sure? The [documentation](http://www.cs.rice.edu/~javaplt/javadoc/concjunit4.7/org/cliffc/high_scale_lib/NonBlockingHashMap.html) for NonBlockingHashMap says it implements java.util.concurrent.ConcurrentMap and java.util.Map. I assumed that because values() is declared in java.util.Map, and because the note about undefined behavior is specified on the iterator on the collection returned by values(), it may be relevant.

Regardless, remove() on the iterator should be faster anyway.

**Comment by aphyr** [comment]
It may result in skipping elements for deletion, which isn't great--but they'll be picked up on the next pass. You're welcome to handle this with an iterator delete if you like. :)
On Oct 19, 2015 3:49 AM, Carlo Alberto Ferraris <notifications@github.com> wrote:@AeroNotix sure? The documentation for NonBlockingHashMap says it implements java.util.concurrent.ConcurrentMap and java.util.Map. I assumed that because values() is declared in java.util.Map, and because the note about undefined behavior is specified on the iterator on the collection returned by values(), it may be relevant.

Regardless, remove() on the iterator should be faster anyway.

**Comment by pyr** [comment]
The eventually consistent behavior of the index is sufficient for now.
