### ISSUE TITLE
Issue with dependencies management.

### ISSUE THREAD

**Issue by st** [riemann/riemann#690]
Dependencies provided by riemann.jar (as of version 0.2.11) are clashing with dependencies provided in EXTRA_CLASSPATH.

Steps to reproduce this issue:
* install riemann 0.2.11
* create a `foo` project depending on kvlt.

in `project-clj` : `[io.nervous/kvlt "0.1.1"]`
* lein uberjar to get `foo-0.1.0-SNAPSHOT-standalone.jar`
* export EXTRA_CLASSPATH

```export EXTRA_CLASSPATH=.../foo/target/foo-0.1.0-SNAPSHOT-standalone.jar```

* write a minimal `config.clj` (standard stuff) containing `(require '[kvlt.core :as kvlt])`
* run `riemann config.clj`

Result:

```
ERROR [2016-05-20 15:52:59,683] main - riemann.bin - Couldn't start
clojure.lang.Compiler$CompilerException: java.lang.IllegalAccessError: have? does not exist, compiling:(taoensso/timbre.clj:1:1)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
...
```

This seems to come from the fact that riemann.jar contains an obsolete version of `com.taoensso/encore`
```
Riemann
[clj-librato "0.0.5" :exclusions [org.jsoup/jsoup]]
 [amazonica "0.3.28" :exclusions [[joda-time]]]
   [com.amazonaws/amazon-kinesis-client "1.1.0" :exclusions [[joda-time]]]
   [com.taoensso/nippy "2.7.0"]
     [com.taoensso/encore "1.11.2"] <<<---  too old
     [net.jpountz.lz4/lz4 "1.2.0"]
     [org.clojure/tools.reader "0.8.9"]
     [org.iq80.snappy/snappy "0.3"]
     [org.tukaani/xz "1.5"]
   [robert/hooke "1.3.0"]
```
```
foo-0.1.0-SNAPSHOT-standalone.jar
 [io.nervous/kvlt "0.1.0" :exclusions [[org.clojure/clojurescript]]]
...
   [com.taoensso/timbre "4.1.4"]
     [com.taoensso/encore "2.18.0"] <<<---
     [io.aviso/pretty "0.1.17"]
```

What am I doing wrong ?
Thanks in advance.

**Comment by pyr** [comment]
Hi @st,

Since you're merging code in riemann's classpath you indeed run the risk of introducing clashes.
As a rule of thumb, you're better off avoiding to bring in uberjars to the classpath as the risk of having
different versions of the same artifacts is high.

There are three ways to circumvent this:

- Add just the JARs you need to the classpath, this will require you to do dependency resolution by hand.
- Use the `depend` function which will pull dependencies using aether
- Use the `depend` function with a pre-generated M2 repository to avoid going out on the internet

See http://riemann.io/api/riemann.config.html#var-depend for details

**Comment by jamtur01** [comment]
Please re-open if you have issues.
