### ISSUE TITLE
Question : Riemann to InfluxDB connection

### ISSUE THREAD

**Issue by sujithnss** [riemann/riemann#697]
Hi 

I'm new to Riemann. Im just trying all the was to connect to InfluxDb from RIemann. But I could not make it working. Im using InfluxDb 0.13 version. Can any one advise a very simplified way to achieve the same. Any code snippets are most welcomed :-)

Best Regards
Sujith P V

**Comment by pradeepchhetri** [comment]
Hi Sujith,

To push riemann events to influxdb, first of all you'll need to create a database (lets give it name *riemann*) using influxdb command: **create database riemann**

Then you can use this basic riemann configuration to push riemann events to influxdb: https://gist.github.com/pradeepchhetri/a33b0577f164beb6930232e3b53acef6

Above configuration file is assuming that you are running the influxdb server on the same host of riemann and on standard port, otherwise you'll need to change this configuration specifying the IP address of the machine running influxdb server.

Once you start riemann with this configuration, you should start seeing events being writtien into influxdb. To verify you can run influxdb command: **show measurements**

Let us know how it goes. If it works please go ahead and close the issue.

Thanks.

**Comment by sujithnss** [comment]
Thanks Pradeep for the quick response. The approach looks very simple and straightforward but unfortunately it didnt work for me.Im bit confused may be something wrong at my end.

Best Regards
Sujith P V

**Comment by shekaralle** [comment]
Hi Pradeep do you have something similar to this to send events to Nagios.
Help would be really appreciated.
