### ISSUE TITLE
Writing empty tag field values to Influx is failing

### ISSUE THREAD

**Issue by anho** [riemann/riemann#732]
Hi,

we currently want to move to a more recent version of Influx as our data storage filled with data coming through Riemann. Unfortunately these current versions of Influx refuse to persist data when the values of a text field are empty. Meaning ``cpu,key1=f1,key2=f2,key3= value=123 1444718454`` or ``cpu,key1=f1,key3=,key2=f2 value=123 1444718454`` will fail. It would be way easier to filter out empty values on Riemann core instead of doing this in the config or the clients pushing data to Riemann. Can we make this happen?

Best regards
Andreas

**Comment by mcorbin** [comment]
Hello,

I don't really know Influxdb and how exactly riemann communicates with it, but i think it can be easy to do.
If i understand correctly, the problem is when a tag is empty (or nil ?)

The problem is probably [here](https://github.com/riemann/riemann/blob/master/src/riemann/influxdb.clj#L32). Something like :

 `
(->> (get event "tags")
         (remove #(or (= "" (second %)) (= nil (second %))))
         (into {}))
`

can maybe solve the problem.

[This test](https://github.com/riemann/riemann/blob/master/test/riemann/influxdb_test.clj#L111) need to be updated too i think.

I can do a PR if the project maintainers are ok with my approach.

**Comment by anho** [comment]
Personally I'd be more than happy seeing this happen. But I'd rather go for fixing the problem [here](https://github.com/riemann/riemann/blob/master/src/riemann/influxdb.clj#L128) or [here](https://github.com/riemann/riemann/blob/master/src/riemann/influxdb.clj#L35).

Plus it seems the same constraints apply for the field values that are written to Influx, so this can be tackled with a more generic approach. The tests ([here](https://github.com/influxdata/influxdb/blob/master/models/points_test.go#L358) and [here](https://github.com/influxdata/influxdb/blob/master/models/points_test.go#L418)) can give some insights in how it should look like.

**Comment by mcorbin** [comment]
Yes, your solution is better.
I made a PR. I remove tags if the value is nil or "". 
The event-fields fn remove fieds if his value is nil, and didn't check if the value is an empty string [(here)](https://github.com/riemann/riemann/blob/master/src/riemann/influxdb.clj#L53)

Do you think check nil is enough ?

**Comment by anho** [comment]
Looks good to me. I've tested it locally with your code and it works like a charm. Thanks a lot, now I obviously have to wait for a release in a few months :)

**Comment by mcorbin** [comment]
Good ;) @pyr @jamtur01 some PRs needs reviews :p
