### ISSUE TITLE
Which part-time constructor to use?

### ISSUE THREAD

**Issue by ulfurinn** [riemann/riemann#884]
I can't find any guidelines re: the choice between `part-time-fast` and `part-time-simple`, and one of them being marked as fast raises some questions:

* is `part-time-simple` slow then? (how much slower?)
* if it's slow, what are the benefits that justify the tradeoff?
* if there aren't any, should it be considered deprecated?

**Comment by mcorbin** [comment]
Hi,

I asked myself the same question with i started contributing to Riemann, and for me the two are slightly differents:

- `part-time-simple` accepts 4 functions: reset, add, side-effects, and finish. `part-time-fast` only accepts create, add, and finish.

- `part-time-simple` uses `riemann.time/once!` repeatedly to schedule tasks while `part-time-fast` uses `periodically-until-expired`  (and `riemann.time/every!`). So, if `part-time-simple` stop receiving events, the periodic task will not be scheduled.

- `part-time-fast` will reset its state when it receives expired events (and because it uses `periodically-until-expired` the scheduled task will be stopped).

I found [this issue](https://github.com/riemann/riemann/issues/19) and the commit referenced interesting.

I don't know how much slower `part-time-simple` is, it would be nice to have some bench indeed.

**Comment by jamtur01** [comment]
Closing.
